### ISSUE TITLE
Automatisation des variables steam

### ISSUE THREAD

**Issue by Exomedia** [Yunaleska-Gaming/Collection-de-jeux#1]
Hello,

Je suis passé sur ton stream et je trouvais le site vraiment sympa donc je me suis permis de regarder les sources et je trouvais ça dommage que tu fasses tout à la main du coup j'ai fait une version modifiée où t'as juste à alimenter un fichier JSON pour créer ou modifier un jeu. Ca calcule :
- Le nombre de jeux
- Les jeux finis à 100%
- Le pourcentage de succès
- Le nombre de succès acquis et totaux

Le fichier assets/json/games_data.json contient les variables des jeux

    {
        "img_src": "bayonetta.jpg",
        "name": "Bayonetta",
        "amount_achievement": "0/50",
        "platined": false
    },
    {
        "img_src": "biped.jpg",
        "name": "Biped",
        "amount_achievement": "10/15",
        "platined": false
    }

Pour les images, juste le nom du fichier présent dans assets/images/steam

Pour les succès : 
- Si la valeur est 0/0, ça utilise la classe "no-achievement-game"
- Si la valeur est 0/x, ça utilise la classe "zero-percent"
- Si la valeur est 10/15 par exemple, ça calcule le pourcentage de largeur de la barre
- Si la valeur est 50/50 par exemple, ça utilise la classe "cent-percent"

Le pourcentage des succès par jeu est calculé automatiquement

Je savais pas si c'était normal que Tunic ait la classe HTML "platined-steam" mais "not-completed-steam" en même temps, j'ai pris en compte uniquement le champ "platined" pour appliquer les deux classes platined et completed.

Dans le fichier assets/scripts/steam.js, à la ligne 17, tu peux décommenter la ligne pour trier automatiquement les jeux par ordre alphabétique
//games.sort((a, b) => a.name.localeCompare(b.name));

J'ai fait ça pour m'occuper un peu, si t'en veux pas c'est pas grave :)

Bonne soirée !

[Yunaleska_steam.zip](https://github.com/user-attachments/files/17651680/Yunaleska_steam.zip)

**Comment by Yunaleska-Gaming** [comment]
Hey @Exomedia ! 

Déjà, désolée de répondre si tard je n'avais pas vu !

Ensuite, énorme merci pour toutes ces informations et aides ainsi que tout ce temps prit pour améliorer mon site !
En effet je fais tout à la main car je n'ai pas toutes les connaissances requises comme tu l'as fait mais franchement c'est exactement ce que je souhaitais ! Je vais pouvoir m'en servir à l'avenir ! Merci encore !

**Comment by Exomedia** [comment]
Avec plaisir :)
